#!/bin/bash

wdir = $(pwd)

msg = "qcap"

cd $1
msg = $2



if test -d ./.git; then

  	git add .
	git commit -m "$msg"
  	git push
  	
else
	git init
	read -p "Enter Repo To Push To: " url

	while [ -z "$url"];
	do
		read -p "Enter Repo To Push To: " url
	done
	
	git remote add origin $url
	
  	git add .
	git commit -m "$msg"	
  	git push --set-upstream origin master
fi

cd $wdir
