#!/bin/bash

#current dir you're in
wdir=$(pwd)



#default msg
msg="qcap"

#if there are no flags and no directory do nothing 
#if there's a directory cd to it
#if there's a flag and no dir obey message flag
#if there's a dir and a flag, cd to dir and obey flag

while getopts ":m:" Option
do
 case $Option in
 	m ) msg="$OPTARG"
 	;;
 	* ) echo "usage"
 	;;
 esac
done

#nothing do nothing

#if there is one arg, cd to it 
if [ $# == 1 ] then
	
fi

#if flag and no dir obey the flag




if test -d ./.git; then

  	git add .
	git commit -m "$msg"
  	git push
  	
else
	git init
	read -p "Enter Repo To Push To: " url

	while [ -z "$url"];
	do
		read -p "Enter Repo To Push To: " url
	done
	
	git remote add origin $url
	
  	git add .
	git commit -m "$msg"	
  	git push --set-upstream origin master
fi

#go back to dir you were originally in
cd $wdir
