#!/bin/bash

wdir=$(pwd)

msg="qcap"

while getopts ":m:" opt; do
  case $opt in
     m)
       msg="$OPTARG"
       ;;
     *)
       echo "Usage: qcap [optional directory] [optional flag -m msg]"
       exit 1
       ;;
  esac
done

#1: no optional dir, no flag,  $# = 0

#2: optional dir and no flag:  $# = 1
#3: no optional dir and flag   $# = 2 (or 1 if they dont put msg)

#4: optional dir and flag      $# = 3 (or 2 if they dont put msg)



if [ $# == 1 ] && [ $msg == "qcap" ]; then
	cd $1
fi


if [ $# == 2 ] || [ $# == 3 ]; then
	cd $1
fi



if test -d ./.git; then

  	git add .
	git commit -m "$msg"
  	git push
  	
else
	git init
	read -p "Enter Repo To Push To: " url

	while [ -z "$url"];
	do
		read -p "Enter Repo To Push To: " url
	done
	
	git remote add origin $url
	
  	git add .
	git commit -m "$msg"	
  	git push --set-upstream origin master
fi

cd $wdir
