#!/bin/bash
echo $#
#current dir you're in
wdir=$(pwd)

#default msg
msg="qcom"

execute () {

	if test -d ./.git; then
	
	  	git add .
		git commit -m "$msg"
	  	git push
	  	
	else
		git init
		read -p "Enter Repo To Push To: " url
	
		while [ -z "$url"];
		do
			read -p "Enter Repo To Push To: " url
		done
		
		git remote add origin $url
		
	  	git add .
		git commit -m "$msg"	
	  	git push --set-upstream origin master
	fi	
}


while getopts "m" flag;
do
 case $flag in
 	m )
 		echo "m flag rec"
 		if [ $# == 1 ]; then
 			echo "test1"
 		
 			echo "no input for -m flag"
 			
 		elif [ $# == 2 ]; then
 			echo "test2"
 			echo $OPTARG
 			execute
 			
 		elif [ $# == 3 ]; then
 			echo "test3"
			cd $1
			msg="OPTARG"
			execute
			cd $wdir
			
 		else
 		
			echo "Too many inputs"
			
 		fi
 			exit 1
 	;;
 	* ) echo "usage"
 		exit 1
 	;;
 esac
done


if [ $# == 0 ]; then
	execute
	exit 1
elif [ $# == 1 ]; then
	cd $1
	execute
	cd $wdir
fi


