#!/bin/bash

wdir=$(pwd)

echo $1

if [ -n "$1" ]; then
	cd $1
fi

if test -d ./.git; then
	read -p "Enter commit message, or leave blank: " msg
  	git add .

	if [ -z "$msg" ]; then
	  	    git commit -m "quick"
	  	else
	  	    git commit -m "$msg"
	  	fi
  	
  	git push
  	
else
	git init
	read -p "Enter Repo To Push To: " url

	while [ -z "$url"];
	do
		read -p "Enter Repo To Push To: " url
	done
	
	git remote add origin $url
  	git add .
  	
  	read -p "Enter commit message, or leave blank: " msg

	if [ -z "$msg" ];  then
	  	    git commit -m "quick"
	  	else
	  	    git commit -m "$msg"
	  	fi
  	
  	git push --set-upstream origin master
fi

cd $wdir
